### ISSUE TITLE
android crash on start

### ISSUE THREAD

**Issue by beqramo** [argyle-systems/argyle-link-react-native#11]
On starting on the android app was crashing and the problem was this after debugging and the current workaround for this is to override `okhttp3` versions. 

Solution
```
    implementation "com.squareup.okhttp3:okhttp"
    implementation "com.squareup.okhttp3:okhttp-bom:4.4.1"
```

Error
```
05-20 11:20:15.489  7780  7953 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
05-20 11:20:15.489  7780  7953 E AndroidRuntime: Process: com.geraldwallet, PID: 7780
05-20 11:20:15.489  7780  7953 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method log(ILjava/lang/String;Ljava/lang/Throwable;)V in class Lokhttp3/internal/platform/Platform; or its super classes (declaration of 'okhttp3.internal.platform.Platform' appears in /data/app/com.geraldwallet-GuMI1Ry_KciDxc8nSr1ARQ==/base.apk!classes3.dex)
05-20 11:20:15.489  7780  7953 E AndroidRuntime: 	at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:114)
05-20 11:20:15.489  7780  7953 E AndroidRuntime: 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:173)
05-20 11:20:15.489  7780  7953 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-20 11:20:15.489  7780  7953 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
05-20 11:20:15.489  7780  7953 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
05-20 11:20:15.489  7780  7953 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-20 11:20:15.489  7780  7953 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-20 11:20:15.489  7780  7953 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
```

Environment
```
"@argyleio/argyle-plugin-react-native": "^3.0.3",
"react-native": "0.64.1",
```

**Comment by Varnius** [comment]
@beqramo thanks for reporting - we will look into it.

**Comment by Varnius** [comment]
@beqramo We are planning to bump version of `okhttp` we are using internally to `4.x` - this should solve your issue and remove the need for workaround. I will update this ticket once it's out.

**Comment by kamalpandey** [comment]
@Varnius is this updated?

I am also getting 

`2021-08-14 21:30:38.409 9432-9547/com.paveapp E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: PID: 9432
    java.lang.NoSuchMethodError: No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie; or its super classes (declaration of 'okhttp3.Cookie' appears in base.apk:classes14.dex)
        at okhttp3.JavaNetCookieJar.saveFromResponse(JavaNetCookieJar.java:45)
        at com.facebook.react.modules.network.ReactCookieJarContainer.saveFromResponse(ReactCookieJarContainer.java:37)
        at okhttp3.internal.http.HttpHeaders.receiveHeaders(HttpHeaders.kt:207)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:85)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
    `
