### ISSUE TITLE
[Android] Argyle SDK incompatible with expo-dev-client package

### ISSUE THREAD

**Issue by cwhenderson20** [argyle-systems/argyle-link-react-native#134]
After installing and configuring `expo-dev-client`, I immediately started seeing a runtime crash before the app even shows a splash screen. Logcat shows the following error:

```
java.lang.NoSuchMethodError: No virtual method loadModules(Ljava/util/List;Z)V in class Lorg/koin/core/Koin; or its super classes (declaration of 'org.koin.core.Koin' appears in /data/app/~~7feirKJl5e7faj7jUJbLcg==/com.gridwise.app-t2UJR02ZKB0gdP6NubVNqA==/base.apk!classes12.dex)
	at expo.modules.devlauncher.DevLauncherController$Companion.initialize$expo_dev_launcher_debug(DevLauncherController.kt:406)
	at expo.modules.devlauncher.DevLauncherController$Companion.initialize(DevLauncherController.kt:438)
	at expo.modules.devlauncher.DevLauncherController$Companion.initialize$default(DevLauncherController.kt:437)
	at expo.modules.devlauncher.DevLauncherPackageDelegate$createApplicationLifecycleListeners$1.onCreate(DevLauncherPackageDelegate.kt:38)
	at expo.modules.ApplicationLifecycleDispatcher.onApplicationCreate(ApplicationLifecycleDispatcher.kt:20)
	at com.gridwise.app.MainApplication.onCreate(MainApplication.kt:87)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

I couldn't find anything _exactly_ matching this error, but [this one](https://github.com/expo/expo/issues/29047) is close.

Similar to the OP there, I initiated a tedious process of elimination and found that removing Argyle from our project resolved the issue immediately. So it seems that there's some kind of incompatibility between the two libraries (maybe having to do with Koin?).

**Environment:**
I originally tried installing `expo-dev-client` on RN 74 / SDK 51 and guessed that maybe upgrading to the latest of those would help. Unfortunately it did not, so I'm listing both versions of everything here as extra data points:
- `argyle-plugin-react-native`: 5.10.1
- `react-native`: 0.74.2 and 0.76.3
- `expo`: 51 and 52
- `expo-dev-client`: 4.0.29 and 5.0.4

We do use Proguard/R8 in release builds, but this is crashing in development, so it's not that.

**Comment by cwhenderson20** [comment]
Minimal reproduction steps:

1. `npx create-expo-app`
2. `npx expo prebuild`
3. `npx expo install expo-dev-client`
4. `npm install @argyleio/argyle-plugin-react-native`
5. `npm run android`

Error:
```
FATAL EXCEPTION: main
Process: com.my.app, PID: 18694
java.lang.NoSuchMethodError: No virtual method loadModules(Ljava/util/List;Z)V in class Lorg/koin/core/Koin; or its super classes (declaration of 'org.koin.core.Koin' appears in /data/app/~~Q3RmoZi6yN8a4zFCygwxUg==/com.my.app-uNwMPxSZ5V01j8xhkWA0iw==/base.apk!classes8.dex)
	at expo.modules.devlauncher.DevLauncherController$Companion.initialize$expo_dev_launcher_debug(DevLauncherController.kt:406)
	at expo.modules.devlauncher.DevLauncherController$Companion.initialize(DevLauncherController.kt:438)
	at expo.modules.devlauncher.DevLauncherController$Companion.initialize$default(DevLauncherController.kt:437)
	at expo.modules.devlauncher.DevLauncherPackageDelegate$createApplicationLifecycleListeners$1.onCreate(DevLauncherPackageDelegate.kt:38)
	at expo.modules.ApplicationLifecycleDispatcher.onApplicationCreate(ApplicationLifecycleDispatcher.kt:20)
	at com.my.app.MainApplication.onCreate(MainApplication.kt:50)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Looks like a similar issue was discussed in https://github.com/argyle-systems/argyle-link-react-native/issues/41.

I also tried forcing resolution to the older version of Koin (3.4.0) as required by `expo-dev-client`, but that simply shifts the crash from startup (where `expo-dev-client` is initialized) to when the Link plugin is opened.

```
api(group: "io.insert-koin", name: "koin-core") {
    version {
        strictly "3.4.0"
    }
}
api(group: "io.insert-koin", name: "koin-android") {
    version {
        strictly "3.4.0"
    }
}
```

**Comment by cwhenderson20** [comment]
Quick update: I patched the `expo-dev-launcher` module (which is what `expo-dev-client` uses internally) to use koin 3.5.6 and that seems to resolve the issue without any obvious ill-effects. 

```patch
@@ -0,0 +1,25 @@
diff --git a/node_modules/expo-dev-launcher/android/build.gradle b/node_modules/expo-dev-launcher/android/build.gradle
index 08897f9..c543627 100644
--- a/node_modules/expo-dev-launcher/android/build.gradle
+++ b/node_modules/expo-dev-launcher/android/build.gradle
@@ -102,16 +102,16 @@ dependencies {
   implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.1")
   implementation "org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion()}"
 
-  def koinVersion = "3.4.0"
+  implementation project.dependencies.platform("io.insert-koin:koin-bom:3.5.6")
 
-  api "io.insert-koin:koin-core:${koinVersion}"
+  api "io.insert-koin:koin-core"
 
   testImplementation 'androidx.test:core:1.4.0'
   testImplementation 'androidx.test:core-ktx:1.4.0'
   testImplementation "com.google.truth:truth:1.1.2"
   testImplementation 'com.squareup.okhttp3:mockwebserver:4.3.1'
-  testImplementation "io.insert-koin:koin-test:${koinVersion}"
-  testImplementation "io.insert-koin:koin-test-junit4:${koinVersion}"
+  testImplementation "io.insert-koin:koin-test"
+  testImplementation "io.insert-koin:koin-test-junit4"
   testImplementation 'io.mockk:mockk:1.12.3'
   testImplementation "org.robolectric:robolectric:4.10"
 }

```

I also previously tried using Gradle dependency resolution rules, which _appeared_ to force `expo-dev-launcher` to use the newer version of koin, but the crash still happened.

I'm not sure that this is technically an issue with either Argyle or Expo, rather an incompatibility between the two. I'll try to reach out to Expo or open a PR there to update koin on their end. However, I'm going to leave this issue open for now as an invitation for the Argyle team to leave their thoughts.

**Comment by cwhenderson20** [comment]
The PR to expo updating the Koin version was merged! I'm still just running this patch locally for the time-being until expo does a new release with the fix, but I'll close this issue for now and open a new one if there continue to be issues.
