### ISSUE TITLE
Android app crash on open argyle link

### ISSUE THREAD

**Issue by hkeithk** [argyle-systems/argyle-link-react-native#30]
Starting from version 4.5.0 we began noticing that our app crashes when opening the argyle link on an android device.

**Comment by Varnius** [comment]
> Starting from version 4.5.0 we began noticing that our app crashes when opening the argyle link on an android device.

Hey @hkeithk - could you share a stack trace?

**Comment by 256hz** [comment]
Hi there, I'm seeing this as well, stack trace is below.  I tested on 4.4.0 before and it was working, although now I get the same error when going back to 4.4.0. So either something has changed on our end to cause the error, or I'm not clearing caches properly when rebuilding or something.

The error message refers to Sentry - does the library use the Sentry logging service internally?  We use Sentry in our app, is it possible there is some namespacing issue behind this?  We had a crash like that with Zendesk before.

We have added `-keep class com.argyle. { _; }` to our Proguard rules.

RN version: 69.1
Argyle version: 4.6.1

Thanks for looking!

```
D/ArgyleExceptionHandler: Initializing Argyle Sentry
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <app-id>, PID: 6338
    java.lang.NoSuchMethodError: No virtual method setEnableUncaughtExceptionHandler(Ljava/lang/Boolean;)V in class Lio/sentry/SentryOptions; or its super classes (declaration of 'io.sentry.SentryOptions' appears in /data/app/<app-id>-Ho6f_9qAbXiFbkRq7RYHtw==/base.apk!classes31.dex)
        at d.c.a(SourceFile:3)
        at d.c.<init>(SourceFile:14)
        at l.s.invoke(SourceFile:375)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:255)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:242)
        at org.koin.core.scope.Scope.get(Scope.kt:205)
        at l.e0.invoke(SourceFile:219)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:255)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:242)
        at org.koin.core.scope.Scope.get(Scope.kt:205)
        at org.koin.androidx.viewmodel.factory.DefaultViewModelFactory.create(DefaultViewModelFactory.kt:13)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:171)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:139)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:44)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:31)
        at com.argyle.ui.features.intro.IntroFragment.e(SourceFile:1)
        at com.argyle.ui.features.intro.IntroFragment.i(SourceFile:4)
        at com.argyle.ui.features.intro.IntroFragment.onViewCreated(SourceFile:5)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3034)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:578)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:264)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
        at android.app.Activity.performStart(Activity.java:7825)
E/AndroidRuntime:     at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process: Sending signal. PID: 6338 SIG: 9
Disconnected from the target VM, address: 'localhost:51097', transport: 'socket'
```

**Comment by Varnius** [comment]
@256hz thanks for the details - what's the Sentry version you are using in your project?
It looks like some breaking change in Sentry lib itself where we would need to bump the version used internally and comply with the changes - will get back to you after we investigate.

**Comment by 256hz** [comment]
@Varnius thanks for the quick reply!  We are using Sentry 4.1.2.

**Comment by Varnius** [comment]
@256hz We found out it's due to a breaking change in Sentry SDK that happened when `Android Sentry SDK 6.0` was released (not to be confused with RN Sentry SDK). We will ship a fix next week.

**Comment by 256hz** [comment]
@Varnius great thank you!

**Comment by Varnius** [comment]
@256hz hey - we are releasing the fix today.

**Comment by Varnius** [comment]
Should be fixed with `4.6.3`
