### ISSUE TITLE
Android - crash on start

### ISSUE THREAD

**Issue by 256hz** [argyle-systems/argyle-link-react-native#33]
Hi there,

Thanks for resolving the Sentry issue on the Android side!

I have found a new crash, also when starting the SDK on Android.  I believe this happens when calling `start` in the SDK before the login call has completed.  Due to our already heavy startup process, we are trying to lazy init whatever we can, so currently we are logging in on the same screen where we're calling `start`.

Would it be possible to create an `onLoggedIn` listener that we could pass a callback to, or something like that?  Or is there another way we could get an indication of logged in state, so we can prevent the user from starting the SDK until login is complete?

Thank you, please let me know if I can provide more info.

RN: 69.1
@argyleio/argyle-plugin-react-native: 4.6.3
device: Pixel 3A emulator

Stack trace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.treecard.app.development, PID: 27766
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.treecard.app.development/com.argyle.ArgyleMainActivity}: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'f.i']
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3685)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'f.i']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:255)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:242)
        at org.koin.core.scope.Scope.get(Scope.kt:205)
        at com.argyle.ArgyleMainActivity$b.invoke(SourceFile:18)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.argyle.ArgyleMainActivity.onCreate(SourceFile:48)
        at android.app.Activity.performCreate(Activity.java:8054)
        at android.app.Activity.performCreate(Activity.java:8034)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3666)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
     Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.argyle.data.network.services.AppService']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:255)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:242)
        at org.koin.core.scope.Scope.get(Scope.kt:205)
        at l.k.invoke(SourceFile:204)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46) 
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53) 
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51) 
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20) 
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51) 
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111) 
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:255) 
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:242) 
        at org.koin.core.scope.Scope.get(Scope.kt:205) 
        at com.argyle.ArgyleMainActivity$b.invoke(SourceFile:18) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at com.argyle.ArgyleMainActivity.onCreate(SourceFile:48) 
        at android.app.Activity.performCreate(Activity.java:8054) 
        at android.app.Activity.performCreate(Activity.java:8034) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3666) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
     Caused by: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
        at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1260)
        at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1633)
        at okhttp3.HttpUrl.get(Unknown Source:2)
        at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:506)
        at l.o.invoke(SourceFile:374)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46) 
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53) 
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51) 
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20) 
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51) 
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111) 
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:255) 
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:242) 
        at org.koin.core.scope.Scope.get(Scope.kt:205) 
        at l.k.invoke(SourceFile:204) 
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54) 
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46) 
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53) 
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51) 
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20) 
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51) 
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111) 
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:255) 
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:242) 
        at org.koin.core.scope.Scope.get(Scope.kt:205) 
        at com.argyle.ArgyleMainActivity$b.invoke(SourceFile:18) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at com.argyle.ArgyleMainActivity.onCreate(SourceFile:48) 
        at android.app.Activity.performCreate(Activity.java:8054) 
        at android.app.Activity.performCreate(Activity.java:8034) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3666) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by zaeem-moves** [comment]
@Varnius I can confirm this is happening on all android devices with Android 12 or higher, for whatever reason, seems to run fine with Android 11.

**Comment by Varnius** [comment]
Hey @zaeem-moves - this might occur due to malformed URL passed to `loginWith` (second param).
if that's not the case, could you provide a snippet of how you initialise Link. Also, checking if an example app from this repo works fine in the same environment would be helpful.

**Comment by zaeem-moves** [comment]
@Varnius I dug into the issue a bit more and seems unrelated. I'll share our process anyways in case it helps someone else out:

We were migrating
From
   `"@argyleio/argyle-plugin-react-native": "^4.1.0",`
 To
   ` "@argyleio/argyle-plugin-react-native": "^4.6.3",`
    
Step 1: With `4.6.3` we had to update our targetSDK version in build.gradle to 31 to use the SDK:
`targetSdkVersion = 31`

Step 2: Due to requirements associated with SDK 30+ we had to make the following three changes as well.

android:exported="true" <-- this had to be added to the main Activity to indicate the indent could called outside of the application.

We ran into this issue (Fix is also detailed on the same page) https://stackoverflow.com/questions/67683149/

Finally, https://stackoverflow.com/questions/67045607/ we ran into this issue due to the android injected library we were using.


After working through all that, Argyle SDK seems to be working fine for both Android and iOS. Basically, our issues had to do with the Android upgrade required to use the SDK, not the Argyle SDK itself.

**Comment by 256hz** [comment]
@Varnius sure - the url I'm using is `https://api-sandbox.argyle.com/v1`.  I'm using it like this

```js
ArgyleSdk.loginWith(Config.ARGYLE_KEY, 'https://api-sandbox.argyle.com/v1', user.token || '');
```

However, if I don't use `.loginWith` before calling `ArgyleSDK.start()`, I get the above crash.  That's probably expected behavior.  I'm wondering if there is a way we can check whether `.loginWith` has succeeded before using `.start`.

**Comment by Varnius** [comment]
@zaeem-moves glad you solved it!

@256hz thing is, `loginWith` actually does not do any kind of authentication but rather simply saves some information in SDKs local state. So you need not to worry about the possible performance hit here. You are correct that it's needed before calling `start` - that a good point for us to improve on in regards of validating configuration in the future.
